
import { Personnel, Rank } from './types';

// O array INITIAL_PERSONNEL define a lista base do efetivo extraída do Mapa de Força.
export const INITIAL_PERSONNEL: Personnel[] = [
  { 
    id: 'admin-007', 
    ant: 0, 
    grad: 'CEL' as Rank, 
    quadro: 'QOPM', 
    nome: 'ADMINISTRADOR SISTEMA', 
    matr: '000.000/0', 
    unid: 'DLF', 
    secao: 'TI', 
    situacao: 'ATIVO', 
    esc: 'EXP', 
    saldoFerias: 30, 
    saldoAbono: 5, 
    role: 'ADMIN'
  },
  { id: '1', ant: 1, grad: 'CEL', quadro: 'QOPM', nome: 'HERBERT DE ALMEIDA JARDIM', matr: '50.508/0', unid: 'DLF', secao: 'DLF', situacao: 'COND D', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '2', ant: 2, grad: 'CEL', quadro: 'QOPM', nome: 'JORGE MARCOS XAVIER DA SILVA', matr: '50.368/1', unid: 'DINFRA', secao: 'DIRETOR', situacao: 'RESTR', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '3', ant: 3, grad: 'CEL', quadro: 'QOPM', nome: 'SIMONEY ALVES SOARES', matr: '50.507/2', unid: 'DALF', secao: 'DIRETOR', situacao: 'COND D', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '4', ant: 4, grad: 'CEL', quadro: 'QOPM', nome: 'EMERSON ALMEIDA CARDOSO', matr: '50.561/7', unid: 'DPTS', secao: 'DIRETOR', situacao: 'COND D', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '5', ant: 5, grad: 'TC', quadro: 'QOPM', nome: 'EVERALDO RODRIGUES ARAGÃO', matr: '50.623/0', unid: 'CMAN', secao: 'CHEFE', situacao: 'COND D', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '10', ant: 10, grad: 'TC', quadro: 'QOPM', nome: 'RODRIGO DE ARAUJO RIBEIRO', matr: '50.805/5', unid: 'DINFRA', secao: 'AT', situacao: '680', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '13', ant: 13, grad: 'MAJ', quadro: 'QOPM', nome: 'RAFAEL RODNEY REIS MELO', matr: '50.914/0', unid: 'DINFRA', secao: 'SPC', situacao: '680', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '22', ant: 22, grad: 'MAJ', quadro: 'QOPM', nome: 'RAFAEL MENDES DANI', matr: '77.193/7', unid: 'DALF', secao: 'SAP', situacao: 'RESTR', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '26', ant: 26, grad: 'MAJ', quadro: 'QOPM', nome: 'MIKHAIL REGIS MUNIZ', matr: '167.765/9', unid: 'DINFRA', secao: 'SAP', situacao: '680', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '29', ant: 29, grad: 'MAJ', quadro: 'QOPM', nome: 'FERNANDA CAROLINE DE OLIVEIRA LEITE PEREIRA', matr: '199.941/9', unid: 'DINFRA', secao: 'SAP', situacao: '680', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '36', ant: 36, grad: 'CAP', quadro: 'QOPM', nome: 'MARCUS UÍTALO MARQUES MENEZES', matr: '730.590/7', unid: 'DINFRA', secao: 'SAP', situacao: '680', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '48', ant: 48, grad: '2º TEN', quadro: 'QOPMA', nome: 'IVANILDO SILVA DE ALMEIDA', matr: '21.471/X', unid: 'DPTS', secao: 'SPL', situacao: 'COND D', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '49', ant: 49, grad: '2º TEN', quadro: 'QOPM', nome: 'MATHEUS VILELA GONÇALVES DA FONSCECA', matr: '736.380/X', unid: 'DALF', secao: 'SS', situacao: 'COND D', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '52', ant: 52, grad: '2º TEN', quadro: 'QOPMA', nome: 'MARIO DE SOUSA CARNEIRO', matr: '21.740/9', unid: 'CMBEL', secao: '', situacao: 'RESTR', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '58', ant: 58, grad: 'ST', quadro: 'QPPMC', nome: 'MAURO CESAR DA SILVA CAVALCANTE', matr: '21.280/6', unid: 'DLF', secao: 'DICC', situacao: 'RESTR', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '74', ant: 74, grad: 'ST', quadro: 'RR', nome: 'MARCELO SOARES DOS SANTOS', matr: '12.706/X', unid: 'CMBEL', secao: '', situacao: 'COND D', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '75', ant: 75, grad: 'ST', quadro: 'RR', nome: 'JURACI PEREIRA DA SILVA', matr: '16.657/X', unid: 'CMAN', secao: '', situacao: 'COND D', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '78', ant: 78, grad: 'ST', quadro: 'RR', nome: 'SEBASTIAO PEREIRA DA SILVA', matr: '20.157/X', unid: 'DLF', secao: 'AEP', situacao: 'COND D', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '83', ant: 83, grad: '1º SGT', quadro: 'QPPMC', nome: 'JURANDI DE MORAIS CARDOSO', matr: '21.020/X', unid: 'CMBEL', secao: '', situacao: 'COND D', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '85', ant: 85, grad: 'ST', quadro: 'QPPMC', nome: 'PATRICIA DE SOUSA NOGUEIRA', matr: '20.980/5', unid: 'DALF', secao: 'SEO', situacao: 'RESTR', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '86', ant: 86, grad: '1º SGT', quadro: 'QPPMC', nome: 'JOSÉ RICARDO PEREIRA DOS SANTOS', matr: '21.366/7', unid: 'DPTS', secao: 'PREFEITURA', situacao: 'RESTR', esc: '12*36', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '94', ant: 94, grad: '1º SGT', quadro: 'QPPMC', nome: 'RENATO AGUIAR REGES', matr: '21.337/3', unid: 'DINFRA', secao: 'SEA', situacao: '680', esc: '12*36', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '100', ant: 100, grad: '1º SGT', quadro: 'QPPMC', nome: 'JACKSON ALVES DE SOUSA', matr: '21.910/X', unid: 'DINFRA', secao: 'SEA', situacao: '680', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '101', ant: 101, grad: '1º SGT', quadro: 'QPPMC', nome: 'ERICK BENAVIDES PAEZ', matr: '22.228/3', unid: 'DLF', secao: 'SARQ', situacao: 'RESTR', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '102', ant: 102, grad: '1º SGT', quadro: 'QPPMC', nome: 'RICARDO NAVES DA SILVA', matr: '21.954/1', unid: 'DINFRA', secao: 'SEA', situacao: 'RESTR', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '104', ant: 104, grad: '1º SGT', quadro: 'QPPMC', nome: 'MARCOS MARTINS PERES', matr: '21.888/X', unid: 'CMBEL', secao: '', situacao: 'COND D', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '118', ant: 118, grad: '1º SGT', quadro: 'QPPMC', nome: 'ELIEZIO DE OLIVEIRA CAMPOS', matr: '22.975/X', unid: 'CMAN', secao: '', situacao: 'COND D', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '126', ant: 126, grad: '1º SGT', quadro: 'QPPMC', nome: 'RICARDO AUGUSTO CAVALCANTE', matr: '23.907/0', unid: 'DALF', secao: 'SAP', situacao: 'RESTR', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '128', ant: 128, grad: '1º SGT', quadro: 'QPPMC', nome: 'TIMOTEO OLIVEIRA BARROS', matr: '24.320/5', unid: 'DINFRA', secao: 'SPC', situacao: 'RESTR', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '134', ant: 134, grad: '1º SGT', quadro: 'QPPMC', nome: 'LUIZ PEDRO DA SILVA', matr: '23.756/6', unid: 'DPTS', secao: 'PREFEITURA', situacao: 'RESTR', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '151', ant: 151, grad: '1º SGT', quadro: 'QPPMC', nome: 'ALAN REUBER DA CRUZ RODRIGUES', matr: '73.009/2', unid: 'DALF', secao: 'SC', situacao: 'RESTR', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '154', ant: 154, grad: '1º SGT', quadro: 'QPPMC', nome: 'MARCELO DOURADO DOS SANTOS', matr: '73.020/3', unid: 'DALF', secao: 'SCON', situacao: 'RESTR', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '155', ant: 155, grad: '1º SGT', quadro: 'QPPMC', nome: 'WANDER DE SOUZA GUEDES', matr: '73.229/X', unid: 'CMBEL', secao: '', situacao: 'COND D', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '158', ant: 158, grad: '1º SGT', quadro: 'QPPMC', nome: 'MOISES OLIVEIRA DE SOUSA', matr: '73.080/7', unid: 'DPTS', secao: 'LEILÃO', situacao: 'RESTR', esc: '12*36', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '176', ant: 176, grad: '1º SGT', quadro: 'QPPMC', nome: 'FERNANDA DE SOUZA RÊGO ROCHA', matr: '72.597/8', unid: 'DPTS', secao: 'SPAT', situacao: 'RESTR', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '190', ant: 190, grad: '2º SGT', quadro: 'QPPMC', nome: 'EDMAR LEMES DE REZENDE', matr: '74.418/2', unid: 'DALF', secao: 'SEO', situacao: 'RESTR', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '197', ant: 197, grad: '2º SGT', quadro: 'QPPMC', nome: 'EDUARDO MOREIRA DIAS FERREIRA', matr: '74.075/6', unid: 'DLF', secao: 'SLOG', situacao: 'RESTR', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '199', ant: 199, grad: '2º SGT', quadro: 'QPPMC', nome: 'MARCELO VIEGAS DE OLIVEIRA', matr: '73.893/X', unid: 'DINFRA', secao: '', situacao: 'COND D', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '202', ant: 202, grad: '2º SGT', quadro: 'QPPMC', nome: 'LEANDRO GOMES PINHO', matr: '74.221/X', unid: 'CMAN', secao: '', situacao: 'COND D', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '203', ant: 203, grad: '2º SGT', quadro: 'QPPMC', nome: 'VALCILEI VARLEI DA SILVA', matr: '73.988/X', unid: 'CMBEL', secao: '', situacao: 'COND D', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '205', ant: 205, grad: '2º SGT', quadro: 'QPPMC', nome: 'WILLIAM CORDOVIL JUNIOR', matr: '74.042/X', unid: 'CMAN', secao: '', situacao: 'COND D', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '208', ant: 208, grad: '2º SGT', quadro: 'QPPMC', nome: 'DEMETRYUS DE OLIVEIRA FIGUEIRA', matr: '73.641/4', unid: 'CMAN', secao: '', situacao: 'RESTR', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '210', ant: 210, grad: '2º SGT', quadro: 'QPPMC', nome: 'ARTHUR RIBEIRO LIMA', matr: '195.748/1', unid: 'DLF', secao: 'DICC', situacao: 'RESTR', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '212', ant: 212, grad: '2º SGT', quadro: 'QPPMC', nome: 'TERCIRGER MENDES COELHO', matr: '196.219/1', unid: 'DALF', secao: 'SEO', situacao: 'RESTR', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '217', ant: 217, grad: '2º SGT', quadro: 'QPPMC', nome: 'LUCIANO DE OLIVEIRA RODRIGUES', matr: '196.885/8', unid: 'DPTS', secao: 'SS', situacao: 'RESTR', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '232', ant: 232, grad: '2º SGT', quadro: 'QPPMC', nome: 'JOSANGELO EDIGENO SILVA CAMARGOS', matr: '215.945/7', unid: 'DINFRA', secao: 'SEA', situacao: 'RESTR', esc: '12*36', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '238', ant: 238, grad: '2º SGT', quadro: 'QPPMC', nome: 'JOÃO RIBEIRO SIRQUEIRA JUNIOR', matr: '215.231/2', unid: 'DLF', secao: 'DICC', situacao: 'RESTR', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '247', ant: 247, grad: '3º SGT', quadro: 'QPPMC', nome: 'DANIEL FARIA DE ABREU FILHO', matr: '731.915/0', unid: 'DALF', secao: 'SEO', situacao: 'RESTR', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '249', ant: 249, grad: '2º SGT', quadro: 'QPPMC', nome: 'ALEXANDRE LOBATO BOUERES', matr: '731.874/X', unid: 'DALF', secao: 'SC', situacao: 'COND D', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '252', ant: 252, grad: '3º SGT', quadro: 'QPPMC', nome: 'WAGNER DIAS DA SILVA', matr: '732.250/X', unid: 'DINFRA', secao: 'AT', situacao: 'COND D', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '255', ant: 255, grad: '3º SGT', quadro: 'QPPMC', nome: 'REGIS DE MORAIS LOPES DOS REIS', matr: '731.512/0', unid: 'DPTS', secao: 'CSO', situacao: 'RESTR', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '258', ant: 258, grad: '2º SGT', quadro: 'QPPMC', nome: 'FERNANDA DINIZ PIRES', matr: '731.463/9', unid: 'DALF', secao: 'SAP', situacao: 'RESTR', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '262', ant: 262, grad: '3º SGT', quadro: 'QPPMC', nome: 'DANIEL MESAK QUINTILIANO', matr: '731.826/X', unid: 'CMAN', secao: '', situacao: 'COND D', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '266', ant: 266, grad: '3º SGT', quadro: 'QPPMC', nome: 'LUCAS MARQUES CAVALCANTE', matr: '731.514/7', unid: 'DALF', secao: 'SCON', situacao: 'RESTR', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '269', ant: 269, grad: '3º SGT', quadro: 'QPPMC', nome: 'JIMMY WISNER ALVES DE SOUZA', matr: '74.283/X', unid: 'CMBEL', secao: '', situacao: 'COND D', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '271', ant: 271, grad: '3º SGT', quadro: 'QPPMC', nome: 'PEDRO RIBEIRO ROCHA', matr: '732.472/3', unid: 'DALF', secao: 'SPL', situacao: 'RESTR', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '272', ant: 272, grad: '3º SGT', quadro: 'QPPMC', nome: 'BRUNO ÁLASSE MENDES JARDIM', matr: '733.043/X', unid: 'DPTS', secao: 'SS', situacao: 'RESTR', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '277', ant: 277, grad: '3º SGT', quadro: 'QPPMC', nome: 'GULTHYERRE CARREIRO DE ARAUJO', matr: '732.992/X', unid: 'CMAN', secao: '', situacao: 'COND D', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '282', ant: 282, grad: '3º SGT', quadro: 'QPPMC', nome: 'VICTOR DINIZ BEZERRA', matr: '733.071/5', unid: 'DLF', secao: 'SAD', situacao: 'RESTR', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '283', ant: 283, grad: '3º SGT', quadro: 'QPPMC', nome: 'LORENA MACHADO DE SOUZA', matr: '732.769/2', unid: 'DALF', secao: 'SAP', situacao: 'RESTR', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '288', ant: 288, grad: '3º SGT', quadro: 'QPPMC', nome: 'JONAS FERREIRA DE SOUZA JUNIOR', matr: '733.193/2', unid: 'DPTS', secao: 'SPAT', situacao: 'RESTR', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '300', ant: 300, grad: 'SD', quadro: 'QPPMC', nome: 'PEDRO AFONSO MARTINS MENDES', matr: '735.648/X', unid: 'DINFRA', secao: 'SAP', situacao: 'CEDIDO', esc: '12*36', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '302', ant: 302, grad: 'CB', quadro: 'QPPMC', nome: 'DENNER FERNANDES LOPES TRISTÃO', matr: '735.682/X', unid: 'DLF', secao: 'GAB', situacao: 'COND D', esc: '12*36', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '304', ant: 304, grad: 'SD', quadro: 'QPPMC', nome: 'LEONARDO CAMPOS DE SOUSA', matr: '735.830/X', unid: 'DINFRA', secao: 'SAP', situacao: 'COND D', esc: '12*36', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '312', ant: 312, grad: 'CB', quadro: 'QPPMC', nome: 'VALCLECIO ALVES VELOSO', matr: '736.036/3', unid: 'DINFRA', secao: 'SAP', situacao: 'RESTR', esc: '12*36', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '333', ant: 333, grad: 'F.CIVIL', quadro: 'CIVIL', nome: 'ALIVANE LEANDRO MELO', matr: '736.301/X', unid: 'DLF', secao: 'GABINETE', situacao: 'COND D', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '339', ant: 339, grad: 'F.CIVIL', quadro: 'CIVIL', nome: 'CAROLINE APPEL MULLER', matr: '738.940/X', unid: 'DINFRA', secao: 'SAP', situacao: 'COND D', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '341', ant: 341, grad: 'F.CIVIL', quadro: 'CIVIL', nome: 'JULIANA TEIXEIRA ROCHA DE SOUSA', matr: '739.090/X', unid: 'DINFRA', secao: 'GABINETE', situacao: 'COND D', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '342', ant: 342, grad: 'F.CIVIL', quadro: 'CIVIL', nome: 'FABIO DIVINO AMADO GONÇALVES', matr: '739.294/X', unid: 'DPTS', secao: 'SPAT', situacao: 'COND D', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' },
  { id: '344', ant: 344, grad: 'F.CIVIL', quadro: 'CIVIL', nome: 'ANA KARINNE CUNHA ALVES', matr: '739.506/X', unid: 'DLF', secao: 'AEP', situacao: 'COND D', esc: 'EXP', saldoFerias: 30, saldoAbono: 5, role: 'USER' }
].map(p => {
  // A senha inicial agora é APENAS OS NÚMEROS da matrícula para facilitar o acesso inicial
  const cleanPass = p.matr.replace(/\D/g, '');
  return {
    ...p,
    password: cleanPass,
    mustChangePassword: true
  } as Personnel;
});
